### ISSUE TITLE
在微信小程序里头, 请求都走了error, 怀疑是微信返回的statusCode在框架中没定义.

### ISSUE THREAD

**Issue by MQL9011** [Yaob1990/miniAxios#3]
我遇到个问题. 微信返的是状态码用的是statusCode. 但是我看框架中定义的是status.
所以在微信小程序里头请求在拦截器里头就走了err.

![image](https://user-images.githubusercontent.com/11871158/150902506-46443cb2-6f42-4634-9f83-f278222cb63f.png)

![image](https://user-images.githubusercontent.com/11871158/150902579-99f89239-51bf-4f44-9399-7cb7c4656832.png)

**Comment by Yaob1990** [comment]
已兼容微信的情况~
